# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Intelligent Systems Lab @ NTNU in Ålesund # Website name
baseURL: 'https://example.com/' # Website URL
schoolLink: "https://www.ntnu.edu/alesund"

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep

# 在文件任意位置（通常放在文件顶端或末尾都可以），添加下面两段：

# ───────────────────────────────────────────────
# 1. 定义一个新的输出格式 “redirects”
#    用来生成 Netlify 所需的 _redirects 文件
# ───────────────────────────────────────────────
outputFormats:
  redirects:
    mediaType: "text/plain"
    baseName: "_redirects"
    isPlainText: true
    notAlternative: true

  headers:
    mediaType: "text/plain"
    baseName: "_headers"
    isPlainText: true
    notAlternative: true

# ───────────────────────────────────────────────
# 2. 告诉 Hugo “home” 这个页面要输出 HTML 之外，还要输出 redirects
# ───────────────────────────────────────────────
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - headers
    - redirects    # ← 新增这一项
  section:
    - HTML
    - RSS